ML-458 Preprocessing Bundle
hpcc-systems/ML_Core pull request #27
Opened 2021-06-21 18:20 UTC by lilyclemson

2021-06-21 18:20 UTC, lilyclemson commented
@RogerDev  Please review.

2021-09-15 17:19 UTC, RogerDev commented on Preprocessing/LabelEncoder.ecl
> + * Note: currently not support Myraid interface.
Should read: "Currently does not support Myriad interface".  Myriad also has a typo.

2021-09-15 17:54 UTC, RogerDev requested changes
A few things to clarify in the comments.  Please redo pull request with new commit.  Don't need to squash the two commits.

2021-09-15 17:54 UTC, RogerDev commented on Preprocessing/MinMaxScaler.ecl
> + * Note: currently not support Myraid interface.
Should be:  "Curently does not support Myriad interface"

2021-09-15 17:54 UTC, RogerDev commented on Preprocessing/OneHotEncoder.ecl
> +  * Support Myraid interface.
Should say:  "Supports Myriad Interface."  Otherwise it is not clear if you are saying that it needs to support Myriad, or if it does.

2021-09-15 17:54 UTC, RogerDev commented on Preprocessing/OneHotEncoder.ecl
> +  * OneHotEncoder
Need to indicate what this does.  For example:

Used to convert each of the designated categorical features to a binary (absent / present) value (i.e. oneHot) for use by algorithms that don't directly support categorical values.  Also can convert back from oneHot encoding to numerical category.  Each categorical field will produce additional features according to its cardinality.  
For example, if there are four possible categories, then the original feature will be replaced by four binary features.  These are placed after all of the non-categorical features in your dataset.

2021-09-15 17:54 UTC, RogerDev commented on Preprocessing/Split.ecl
> + * Note: currently not support Myraid interface.
Same comment as above.

2021-09-15 17:54 UTC, RogerDev commented on Preprocessing/Split.ecl
> + * @param trainSize: REAL4, DEFAULT = 0.0.
If these are sizes (i.e. record counts), why is this a real?  These must be fractions of the record count???  Please specify.

2021-09-15 17:54 UTC, RogerDev commented on Preprocessing/StandardScaler.ecl
> +  * Transform the input data to a standard normally distributed data with zero mean and
Should read:  Standardize the data by mapping to zero mean and standard deviation of 1.0.

2021-09-15 17:54 UTC, RogerDev commented on Preprocessing/StandardScaler.ecl
> +  * Note: currently not support Myraid interface.
Same as above

2021-09-15 17:54 UTC, RogerDev commented on Preprocessing/StratifiedSplit.ecl
> + * Note: currently not support Myraid interface.
Same

2021-09-15 17:54 UTC, RogerDev commented on Preprocessing/Utils/AppendNF.ecl
> + * Appends a numeric field dataset to another
It is not clear whether this appends vertically, by adjusting the ids, or horizontally by adjusting number field.  Please clarify

2021-09-15 17:54 UTC, RogerDev commented on Preprocessing/Normalizer.ecl
> + * Normalize the data with below options:
I'm not sure why we would want to do this???  Please explain the use, or remove this module.

2021-09-16 14:01 UTC, lilyclemson commented
@RogerDev PR is updated based on your comments. Please review.

2022-02-23 22:10 UTC, RogerDev approved these changes
Github is flagging a bunch of files as not having a final newline.  I don't know if that's actually a problem, but other than that should be good to go.

2022-02-24 09:54 UTC, merged